### ISSUE TITLE
Could not find a declaration file for module 'chakra-multiselect'

### ISSUE THREAD

**Issue by jbloggz** [bmartel/chakra-multiselect#32] opened 2023-10-09 00:08 UTC
I'd like to use this componenet in my project, however when I try to import it I get the following typescript error:

`Could not find a declaration file for module 'chakra-multiselect'.`

![image](https://github.com/bmartel/chakra-multiselect/assets/29333413/91edbde6-0f3b-4f97-a287-06a58e662343)

Is this something wrong on my end or with the library?

**Comment by bmartel** [comment] 2024-01-20 20:49
Hey there 👋. This would be a result of Typescript 5 and using `moduleResolution: "bundler"`. That has to be fixed on the library side which I believe may be corrected with the latest published release. Please give it a try and let me know if there are still issues.

**Comment by bmartel** [comment] 2024-01-22 12:30
I'm going to close this one as fixed, I do not get this error anymore since the adjustment to the package.json exports on a previous minimal reproduction: https://stackblitz.com/edit/vitejs-vite-1jhxbn?file=tsconfig.json

**Closed as completed** 2024-01-22 12:30 UTC
